baseurl = "https://www.romange.com/"
languageCode = "en-us"
title = "Это неправильные пчелы"

# Enable comments by entering your Disqus shortname
disqusShortname = "romange"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-107146718-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
publishDir = "public"
buildDrafts = false

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "Roman Gershman"
    bio = "Programmer"
    location = "Tel Aviv"
    site_description = "The wrong sort of bees"
    copyright  = "Roman Gershman"
    avatar = "css/images/avatar.png"

    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "romange@gmail.com"
    logo = "css/images/7.png"
    disable_mathjax = true # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "Jan 2nd 2006"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "About"
    link   = "about/"


# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/romange"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "romange"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
